### PR TITLE
Robustly discover packages with @manypkg

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Resolves: https://github.com/embroider-build/release-plan/issues/46
Requires: https://github.com/ef4/lerna-changelog/pull/8 (included in this PR, as it is one half of the solution to #46)

Can test on your own repo with an override:
```js
"pnpm": {
  "overrides": {
    "release-plan": "github:embroider-build/release-plan#tmp-manypkg-dist"
  }
}
```

Additionally, this should unlock the ability to remove `--singlePackage`, as `@manypkg` _just works_.

### CODE REVIEW

**Review by ef4 — APPROVED** [review]

**Review by mansona — CHANGES_REQUESTED** [review]
As discussed in the tooling meeting: we should add some basic tests here before proceeding

**Comment by NullVoxPopuli** [comment]
> As discussed in the tooling meeting: we should add some basic tests here before proceeding


done -- I added two tests for some scenarios that I'm most immediately concerned with.

**Review by mansona — APPROVED** [review]
Looks good! thanks

**Comment by mansona** [comment]
I marked this as an enhancement because it changes the internal implementation of something. Really it's a bugfix because it's trying to fix a specific bug but it's too much of a big change to just be considered a bugfix 👍

**Pull request merged**
